### PR TITLE
updated brance

### PR DESCRIPTION
**Pull request by xiyuanzhou**

### CODE REVIEW

**Comment by xiyuanzhou** [comment]
User databases have been created, updated backend server

**Comment by xiyuanzhou** [comment]
For the HTML files, I created for testing the backend

**Comment by TrustfulDev** [comment]
React integration with Django needs to be done in order for the frontend team to test functionality. I trust you will do so.

**Comment by TrustfulDev** [comment]
@rhedgeco can you look into the API/secret key? I can't find the secret_key or an API key being used anywhere for the database. Unless Django handles everything, and I'm overthinking it. Thanks in advance!

**Review by TrustfulDev — APPROVED** [review]
Everything looks good! The only things left to do is React integration and ensuring that the database is secure.

**Comment by xiyuanzhou** [comment]
Needed python-dotenv for (.env) Django. I will fix that tonight.

**Comment by rhedgeco** [comment]
Everything looks good, im just going to insert some instructions on how to set up with a virtual environment

**Review by rhedgeco — APPROVED** [review]
:+1:

**Comment by rhedgeco** [comment]
@xiyuanzhou can you verify that the `venv` setup works on your end? After that go ahead and squash and merge

**Comment by xiyuanzhou** [comment]
venv works

**Pull request merged**
