### PR TITLE
React + Django Integration for Routing & Authentication

### PR DESCRIPTION
**Pull request by xiyuanzhou**
POST and GET

### CODE REVIEW

**Comment by TrustfulDev** [comment]
Reminder: As we add routes, match the url in Server/urls.py

App.js
`<Route path='/' element={<HomePage />} />`
`<Route path='/login' element={<Login />} />`
`<Route path='/register' element={<Registerexample />} />`

urls.py
`path('', TemplateView.as_view(template_name='index.html')),`
`path('login/', TemplateView.as_view(template_name='index.html')),`
`path('register/', TemplateView.as_view(template_name='index.html')),`

**Review by TrustfulDev — APPROVED** [review]
Traditional authentication works like a charm! The navbar correctly changes state and logging out works as intended. 

NOTE: Google authentication is still a work in progress, but we should open another PR for that.
Also, need to somehow grab the user data in the Frontend.

**Review by rhedgeco — APPROVED** [review]
Looks good to me. Functions as expected.

I second that separate google auth PR idea. Would be nice to split it up and have this merged.

**Comment by rhedgeco** [comment]
resolves #10 

Add a new issue for the google auth problem please

**Pull request merged**
