### PR TITLE
Login & SignUp pages

### PR DESCRIPTION
**Pull request by TrustfulDev**
Revamped Surafels work on the two pages. Adjusted CSS to make the pages look like the design and added responsiveness. The mobile responsiveness can use some work, but they are there as a placeholder for now.

NOTE: Navbar has to now be manually placed per page since the login & sign-up pages do not have the navbar. This can be changed.

### CODE REVIEW

**Review by Surafelgit — COMMENTED** [review]
Looks good!

**Review by Surafelgit — APPROVED** [review]

**Comment by TrustfulDev** [comment]
Left side us original; right side is revamped.
image

**Comment by reddesignsguy** [comment]
looks great!

**Review by reddesignsguy — APPROVED** [review]
looks great

**Pull request merged**
