### PR TITLE
Search Page

### PR DESCRIPTION
**Pull request by reddesignsguy**
Overview:
image

### CODE REVIEW

**Comment by TrustfulDev** [comment]
There are so many conflicts... I'm going to merge main into this branch and resolve all the conflicts that way.

**Comment by TrustfulDev** [comment]
Ok... testing a merge with main right now and it is going TERRIBLE. Everything is just wrong. There are most likely global css selectors somewhere in the files that are messing things up.

**Review by TrustfulDev — APPROVED** [review]
I finished fixing all the bugs that occured with merging main into this branch. We need to merge this asap to start implementing the functionality of the searchbar in the home page.

**Comment by TrustfulDev** [comment]
The data is passed in as an object: `state = { location: "string", checkDates: {startDate, endDate}, travelers: int, rooms: int }`

**Review by rhedgeco — APPROVED** [review]
Sorry it took a while. Had some problems running on the server, and had to make sure it was my problem and not a problem with your code. Good stuff @reddesignsguy :+1:

**Pull request merged**
