### PR TITLE
global css variables

### PR DESCRIPTION
**Pull request by reddesignsguy**

### CODE REVIEW

**Comment by reddesignsguy** [comment]
global css variables

**Review by TrustfulDev — APPROVED** [review]
Make sure you link the font inside ../public/index.html if it's from google or somewhere online. Other than that, the colors look good!

**Comment by ChoyeeMyae** [comment]
nice work

**Review by reddesignsguy — COMMENTED** [review]
yes

**Review by ChoyeeMyae — APPROVED** [review]
approved merge

**Pull request merged**
